spring.application.name=rest-apis

# MySQL Database
spring.datasource.url=jdbc:mysql://localhost:3306/rest_api_db
spring.datasource.username=root
spring.datasource.password=Nikhil@123

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# MySQL Driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver